#!/bin/bash

FILE="/tmp/screenshot.png"
BLUR="/tmp/screenshotblur.png"
if [ -f $FILE ];
then
  rm "$FILE"
fi
if [ -f $BLUR ];
then
  rm "$BLUR"
fi
scrot "$FILE"
convert "$FILE" -blur 0x5 "$BLUR"
i3lock -i "$BLUR"
