#!/bin/bash
bat=$(acpi|tr ' ' '\n' | grep '%' | tr ',' ' ')
stat=$(acpi | tr ' ' '\n'  | grep , | grep -v % | sed 's/,//g')
time=$(date +%R)
addr=$(ip addr show dev wlp3s0 scope global | grep inet | awk '{print $2}')
bright=$(cat /sys/class/backlight/intel_backlight/brightness)
notify-send -u low $stat "Battery: $bat\nTime: $time\nBrightness: $bright\nAddr: $addr"
