#!/usr/bin/env bash

if [ -f ~/.dmenurc ]; then
	. ~/.dmenurc
else
	DMENU='dmenu -i'
fi

WS="$(cat ~/.dirhist | $DMENU -p 'dir$ ')"

if grep -q "$WS" ~/.dirhist ; then
	echo "Exists in history"
else
	echo $WS >> ~/.dirhist
fi

[ "$WS" ] && urxvt -e zsh -c "ranger $WS"
