#!/bin/bash

# Reads all dirs of wallpaper folder to set the mood

if [ -f ~/.dmenurc ]; then
	. ~/.dmenurc
else
	DMENU='dmenu -i'
fi

echo $(find ~/pictures/wallpaper/ -type d -print | cut -c 32- | $DMENU) > ~/pictures/wallmood.txt
