#!/bin/bash

# Searches through my MPD database using dmenu, layered multiple times

if [ -f ~/.dmenurc ]; then
	. ~/.dmenurc
else
	DMENU='dmenu -i'
fi

CHOICE=$(cat ~/scripts/dmenu_mpc_options2.txt | $DMENU -p 'MPD:')

case $CHOICE in
	Add)
		TYPE=$(cat ~/scripts/dmenu_mpc_options.txt | $DMENU -p 'Type:')
		SPECIFIC="$(mpc --no-status list $TYPE | $DMENU -p 'Specifically:')"
		mpc findadd $TYPE "$SPECIFIC"
	;;
	Insert)
		# Still very much a work in progress
		TYPE=$(cat ~/scripts/dmenu_mpc_options.txt | $DMENU -p 'Type:')
		SPECIFIC="$(mpc --no-status list $TYPE | $DMENU -p 'Specifically:')"
		FILES=$(mpc search $TYPE "$SPECIFIC")
		echo $FILES
		mpc insert "$FILES"
	;;
	Play)
		TYPE=$(cat ~/scripts/dmenu_mpc_options.txt | $DMENU -p 'Type:')
		SPECIFIC="$(mpc --no-status list $TYPE | $DMENU -p 'Specifically:')"
		mpc clear
		mpc findadd $TYPE "$SPECIFIC"
		mpc play
	;;
	Clear)
		mpc clear
	;;
	Settings)
	;;
	Playlist)
		PLAY=$(mpc lsplaylists | $DMENU -p 'Playlist Name:')
		if [ "$PLAY" != "" ]; then
			mpc clear
			mpc load $PLAY
			mpc play
		fi
	;;
esac
